<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountriesRegionsAndCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        
        $countries = [
            ['name' => 'Afganistán', 'code' => 'AF', 'is_other' => false],
            ['name' => 'Åland', 'code' => 'AX', 'is_other' => false],
            ['name' => 'Albania', 'code' => 'AL', 'is_other' => false],
            ['name' => 'Alemania', 'code' => 'DE', 'is_other' => false],
            ['name' => 'Andorra', 'code' => 'AD', 'is_other' => false],
            ['name' => 'Angola', 'code' => 'AO', 'is_other' => false],
            ['name' => 'Anguila', 'code' => 'AI', 'is_other' => false],
            ['name' => 'Antártida', 'code' => 'AQ', 'is_other' => false],
            ['name' => 'Antigua y Barbuda', 'code' => 'AG', 'is_other' => false],
            ['name' => 'Arabia Saudita', 'code' => 'SA', 'is_other' => false],
            ['name' => 'Argelia', 'code' => 'DZ', 'is_other' => false],
            ['name' => 'Argentina', 'code' => 'AR', 'is_other' => false],
            ['name' => 'Armenia', 'code' => 'AM', 'is_other' => false],
            ['name' => 'Aruba', 'code' => 'AW', 'is_other' => false],
            ['name' => 'Australia', 'code' => 'AU', 'is_other' => false],
            ['name' => 'Austria', 'code' => 'AT', 'is_other' => false],
            ['name' => 'Azerbaiyán', 'code' => 'AZ', 'is_other' => false],
            ['name' => 'Bahamas', 'code' => 'BS', 'is_other' => false],
            ['name' => 'Bangladés', 'code' => 'BD', 'is_other' => false],
            ['name' => 'Barbados', 'code' => 'BB', 'is_other' => false],
            ['name' => 'Baréin', 'code' => 'BH', 'is_other' => false],
            ['name' => 'Bélgica', 'code' => 'BE', 'is_other' => false],
            ['name' => 'Belice', 'code' => 'BZ', 'is_other' => false],
            ['name' => 'Benín', 'code' => 'BJ', 'is_other' => false],
            ['name' => 'Bermudas', 'code' => 'BM', 'is_other' => false],
            ['name' => 'Bielorrusia', 'code' => 'BY', 'is_other' => false],
            ['name' => 'Bolivia', 'code' => 'BO', 'is_other' => false],
            ['name' => 'Bonaire, San Eustaquio y Saba', 'code' => 'BQ', 'is_other' => false],
            ['name' => 'Bosnia y Herzegovina', 'code' => 'BA', 'is_other' => false],
            ['name' => 'Botsuana', 'code' => 'BW', 'is_other' => false],
            ['name' => 'Brasil', 'code' => 'BR', 'is_other' => false],
            ['name' => 'Brunéi', 'code' => 'BN', 'is_other' => false],
            ['name' => 'Bulgaria', 'code' => 'BG', 'is_other' => false],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'is_other' => false],
            ['name' => 'Burundi', 'code' => 'BI', 'is_other' => false],
            ['name' => 'Bután', 'code' => 'BT', 'is_other' => false],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'is_other' => false],
            ['name' => 'Camboya', 'code' => 'KH', 'is_other' => false],
            ['name' => 'Camerún', 'code' => 'CM', 'is_other' => false],
            ['name' => 'Canadá', 'code' => 'CA', 'is_other' => false],
            ['name' => 'Catar', 'code' => 'QA', 'is_other' => false],
            ['name' => 'Chad', 'code' => 'TD', 'is_other' => false],
            ['name' => 'Chile', 'code' => 'CL', 'is_other' => false],
            ['name' => 'China', 'code' => 'CN', 'is_other' => false],
            ['name' => 'Chipre', 'code' => 'CY', 'is_other' => false],
            ['name' => 'Colombia', 'code' => 'CO', 'is_other' => false],
            ['name' => 'Comoras', 'code' => 'KM', 'is_other' => false],
            ['name' => 'Corea del Norte', 'code' => 'KP', 'is_other' => false],
            ['name' => 'Corea del Sur', 'code' => 'KR', 'is_other' => false],
            ['name' => 'Costa de Marfil', 'code' => 'CI', 'is_other' => false],
            ['name' => 'Costa Rica', 'code' => 'CR', 'is_other' => false],
            ['name' => 'Croacia', 'code' => 'HR', 'is_other' => false],
            ['name' => 'Cuba', 'code' => 'CU', 'is_other' => false],
            ['name' => 'Curazao', 'code' => 'CW', 'is_other' => false],
            ['name' => 'Dinamarca', 'code' => 'DK', 'is_other' => false],
            ['name' => 'Dominica', 'code' => 'DM', 'is_other' => false],
            ['name' => 'Ecuador', 'code' => 'EC', 'is_other' => false],
            ['name' => 'Egipto', 'code' => 'EG', 'is_other' => false],
            ['name' => 'El Salvador', 'code' => 'SV', 'is_other' => false],
            ['name' => 'Emiratos Árabes Unidos', 'code' => 'AE', 'is_other' => false],
            ['name' => 'Eritrea', 'code' => 'ER', 'is_other' => false],
            ['name' => 'Eslovaquia', 'code' => 'SK', 'is_other' => false],
            ['name' => 'Eslovenia', 'code' => 'SI', 'is_other' => false],
            ['name' => 'España', 'code' => 'ES', 'is_other' => false],
            ['name' => 'Estados Unidos', 'code' => 'US', 'is_other' => false],
            ['name' => 'Estonia', 'code' => 'EE', 'is_other' => false],
            ['name' => 'Etiopía', 'code' => 'ET', 'is_other' => false],
            ['name' => 'Filipinas', 'code' => 'PH', 'is_other' => false],
            ['name' => 'Finlandia', 'code' => 'FI', 'is_other' => false],
            ['name' => 'Fiyi', 'code' => 'FJ', 'is_other' => false],
            ['name' => 'Francia', 'code' => 'FR', 'is_other' => false],
            ['name' => 'Gabón', 'code' => 'GA', 'is_other' => false],
            ['name' => 'Gambia', 'code' => 'GM', 'is_other' => false],
            ['name' => 'Georgia', 'code' => 'GE', 'is_other' => false],
            ['name' => 'Ghana', 'code' => 'GH', 'is_other' => false],
            ['name' => 'Gibraltar', 'code' => 'GI', 'is_other' => false],
            ['name' => 'Granada', 'code' => 'GD', 'is_other' => false],
            ['name' => 'Grecia', 'code' => 'GR', 'is_other' => false],
            ['name' => 'Groenlandia', 'code' => 'GL', 'is_other' => false],
            ['name' => 'Guadalupe', 'code' => 'GP', 'is_other' => false],
            ['name' => 'Guam', 'code' => 'GU', 'is_other' => false],
            ['name' => 'Guatemala', 'code' => 'GT', 'is_other' => false],
            ['name' => 'Guayana Francesa', 'code' => 'GF', 'is_other' => false],
            ['name' => 'Guernsey', 'code' => 'GG', 'is_other' => false],
            ['name' => 'Guinea', 'code' => 'GN', 'is_other' => false],
            ['name' => 'Guinea-Bisáu', 'code' => 'GW', 'is_other' => false],
            ['name' => 'Guinea Ecuatorial', 'code' => 'GQ', 'is_other' => false],
            ['name' => 'Guyana', 'code' => 'GY', 'is_other' => false],
            ['name' => 'Haití', 'code' => 'HT', 'is_other' => false],
            ['name' => 'Honduras', 'code' => 'HN', 'is_other' => false],
            ['name' => 'Hong Kong', 'code' => 'HK', 'is_other' => false],
            ['name' => 'Hungría', 'code' => 'HU', 'is_other' => false],
            ['name' => 'India', 'code' => 'IN', 'is_other' => false],
            ['name' => 'Indonesia', 'code' => 'ID', 'is_other' => false],
            ['name' => 'Irak', 'code' => 'IQ', 'is_other' => false],
            ['name' => 'Irán', 'code' => 'IR', 'is_other' => false],
            ['name' => 'Irlanda', 'code' => 'IE', 'is_other' => false],
            ['name' => 'Isla Bouvet', 'code' => 'BV', 'is_other' => false],
            ['name' => 'Isla de Man', 'code' => 'IM', 'is_other' => false],
            ['name' => 'Isla de Navidad', 'code' => 'CX', 'is_other' => false],
            ['name' => 'Islandia', 'code' => 'IS', 'is_other' => false],
            ['name' => 'Islas Caimán', 'code' => 'KY', 'is_other' => false],
            ['name' => 'Islas Cocos', 'code' => 'CC', 'is_other' => false],
            ['name' => 'Islas Cook', 'code' => 'CK', 'is_other' => false],
            ['name' => 'Islas Feroe', 'code' => 'FO', 'is_other' => false],
            ['name' => 'Islas Georgias del Sur y Sandwich del Sur', 'code' => 'GS', 'is_other' => false],
            ['name' => 'Islas Heard y McDonald', 'code' => 'HM', 'is_other' => false],
            ['name' => 'Islas Malvinas', 'code' => 'FK', 'is_other' => false],
            ['name' => 'Islas Marianas del Norte', 'code' => 'MP', 'is_other' => false],
            ['name' => 'Islas Marshall', 'code' => 'MH', 'is_other' => false],
            ['name' => 'Islas Pitcairn', 'code' => 'PN', 'is_other' => false],
            ['name' => 'Islas Salomón', 'code' => 'SB', 'is_other' => false],
            ['name' => 'Islas Turcas y Caicos', 'code' => 'TC', 'is_other' => false],
            ['name' => 'Islas Ultramarinas Menores de los Estados Unidos', 'code' => 'UM', 'is_other' => false],
            ['name' => 'Islas Vírgenes Británicas', 'code' => 'VG', 'is_other' => false],
            ['name' => 'Islas Vírgenes de los Estados Unidos', 'code' => 'VI', 'is_other' => false],
            ['name' => 'Israel', 'code' => 'IL', 'is_other' => false],
            ['name' => 'Italia', 'code' => 'IT', 'is_other' => false],
            ['name' => 'Jamaica', 'code' => 'JM', 'is_other' => false],
            ['name' => 'Japón', 'code' => 'JP', 'is_other' => false],
            ['name' => 'Jersey', 'code' => 'JE', 'is_other' => false],
            ['name' => 'Jordania', 'code' => 'JO', 'is_other' => false],
            ['name' => 'Kazajistán', 'code' => 'KZ', 'is_other' => false],
            ['name' => 'Kenia', 'code' => 'KE', 'is_other' => false],
            ['name' => 'Kirguistán', 'code' => 'KG', 'is_other' => false],
            ['name' => 'Kiribati', 'code' => 'KI', 'is_other' => false],
            ['name' => 'Kuwait', 'code' => 'KW', 'is_other' => false],
            ['name' => 'Laos', 'code' => 'LA', 'is_other' => false],
            ['name' => 'Lesoto', 'code' => 'LS', 'is_other' => false],
            ['name' => 'Letonia', 'code' => 'LV', 'is_other' => false],
            ['name' => 'Líbano', 'code' => 'LB', 'is_other' => false],
            ['name' => 'Liberia', 'code' => 'LR', 'is_other' => false],
            ['name' => 'Libia', 'code' => 'LY', 'is_other' => false],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'is_other' => false],
            ['name' => 'Lituania', 'code' => 'LT', 'is_other' => false],
            ['name' => 'Luxemburgo', 'code' => 'LU', 'is_other' => false],
            ['name' => 'Macao', 'code' => 'MO', 'is_other' => false],
            ['name' => 'Macedonia del Norte', 'code' => 'MK', 'is_other' => false],
            ['name' => 'Madagascar', 'code' => 'MG', 'is_other' => false],
            ['name' => 'Malasia', 'code' => 'MY', 'is_other' => false],
            ['name' => 'Malaui', 'code' => 'MW', 'is_other' => false],
            ['name' => 'Maldivas', 'code' => 'MV', 'is_other' => false],
            ['name' => 'Mali', 'code' => 'ML', 'is_other' => false],
            ['name' => 'Malta', 'code' => 'MT', 'is_other' => false],
            ['name' => 'Marruecos', 'code' => 'MA', 'is_other' => false],
            ['name' => 'Martinica', 'code' => 'MQ', 'is_other' => false],
            ['name' => 'Mauricio', 'code' => 'MU', 'is_other' => false],
            ['name' => 'Mauritania', 'code' => 'MR', 'is_other' => false],
            ['name' => 'Mayotte', 'code' => 'YT', 'is_other' => false],
            ['name' => 'México', 'code' => 'MX', 'is_other' => false],
            ['name' => 'Micronesia', 'code' => 'FM', 'is_other' => false],
            ['name' => 'Moldavia', 'code' => 'MD', 'is_other' => false],
            ['name' => 'Mónaco', 'code' => 'MC', 'is_other' => false],
            ['name' => 'Mongolia', 'code' => 'MN', 'is_other' => false],
            ['name' => 'Montenegro', 'code' => 'ME', 'is_other' => false],
            ['name' => 'Montserrat', 'code' => 'MS', 'is_other' => false],
            ['name' => 'Mozambique', 'code' => 'MZ', 'is_other' => false],
            ['name' => 'Birmania', 'code' => 'MM', 'is_other' => false],
            ['name' => 'Namibia', 'code' => 'NA', 'is_other' => false],
            ['name' => 'Nauru', 'code' => 'NR', 'is_other' => false],
            ['name' => 'Nepal', 'code' => 'NP', 'is_other' => false],
            ['name' => 'Nicaragua', 'code' => 'NI', 'is_other' => false],
            ['name' => 'Níger', 'code' => 'NE', 'is_other' => false],
            ['name' => 'Nigeria', 'code' => 'NG', 'is_other' => false],
            ['name' => 'Niue', 'code' => 'NU', 'is_other' => false],
            ['name' => 'Isla Norfolk', 'code' => 'NF', 'is_other' => false],
            ['name' => 'Noruega', 'code' => 'NO', 'is_other' => false],
            ['name' => 'Nueva Caledonia', 'code' => 'NC', 'is_other' => false],
            ['name' => 'Nueva Zelanda', 'code' => 'NZ', 'is_other' => false],
            ['name' => 'Omán', 'code' => 'OM', 'is_other' => false],
            ['name' => 'Países Bajos', 'code' => 'NL', 'is_other' => false],
            ['name' => 'Pakistán', 'code' => 'PK', 'is_other' => false],
            ['name' => 'Palaos', 'code' => 'PW', 'is_other' => false],
            ['name' => 'Palestina', 'code' => 'PS', 'is_other' => false],
            ['name' => 'Panamá', 'code' => 'PA', 'is_other' => false],
            ['name' => 'Papúa Nueva Guinea', 'code' => 'PG', 'is_other' => false],
            ['name' => 'Paraguay', 'code' => 'PY', 'is_other' => false],
            ['name' => 'Perú', 'code' => 'PE', 'is_other' => false],
            ['name' => 'Polinesia Francesa', 'code' => 'PF', 'is_other' => false],
            ['name' => 'Polonia', 'code' => 'PL', 'is_other' => false],
            ['name' => 'Portugal', 'code' => 'PT', 'is_other' => false],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'is_other' => false],
            ['name' => 'Reino Unido', 'code' => 'GB', 'is_other' => false],
            ['name' => 'República Árabe Saharaui Democrática', 'code' => 'EH', 'is_other' => false],
            ['name' => 'República Centroafricana', 'code' => 'CF', 'is_other' => false],
            ['name' => 'República Checa', 'code' => 'CZ', 'is_other' => false],
            ['name' => 'República del Congo', 'code' => 'CG', 'is_other' => false],
            ['name' => 'República Democrática del Congo', 'code' => 'CD', 'is_other' => false],
            ['name' => 'República Dominicana', 'code' => 'DO', 'is_other' => false],
            ['name' => 'Reunión', 'code' => 'RE', 'is_other' => false],
            ['name' => 'Ruanda', 'code' => 'RW', 'is_other' => false],
            ['name' => 'Rumania', 'code' => 'RO', 'is_other' => false],
            ['name' => 'Rusia', 'code' => 'RU', 'is_other' => false],
            ['name' => 'Samoa', 'code' => 'WS', 'is_other' => false],
            ['name' => 'Samoa Americana', 'code' => 'AS', 'is_other' => false],
            ['name' => 'San Bartolomé', 'code' => 'BL', 'is_other' => false],
            ['name' => 'San Cristóbal y Nieves', 'code' => 'KN', 'is_other' => false],
            ['name' => 'San Marino', 'code' => 'SM', 'is_other' => false],
            ['name' => 'San Martín', 'code' => 'MF', 'is_other' => false],
            ['name' => 'San Pedro y Miquelón', 'code' => 'PM', 'is_other' => false],
            ['name' => 'San Vicente y las Granadinas', 'code' => 'VC', 'is_other' => false],
            ['name' => 'Santa Elena, Ascensión y Tristán de Acuña', 'code' => 'SH', 'is_other' => false],
            ['name' => 'Santa Lucía', 'code' => 'LC', 'is_other' => false],
            ['name' => 'Santo Tomé y Príncipe', 'code' => 'ST', 'is_other' => false],
            ['name' => 'Senegal', 'code' => 'SN', 'is_other' => false],
            ['name' => 'Serbia', 'code' => 'RS', 'is_other' => false],
            ['name' => 'Seychelles', 'code' => 'SC', 'is_other' => false],
            ['name' => 'Sierra Leona', 'code' => 'SL', 'is_other' => false],
            ['name' => 'Singapur', 'code' => 'SG', 'is_other' => false],
            ['name' => 'San Martín', 'code' => 'SX', 'is_other' => false],
            ['name' => 'Siria', 'code' => 'SY', 'is_other' => false],
            ['name' => 'Somalia', 'code' => 'SO', 'is_other' => false],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'is_other' => false],
            ['name' => 'Suazilandia', 'code' => 'SZ', 'is_other' => false],
            ['name' => 'Sudáfrica', 'code' => 'ZA', 'is_other' => false],
            ['name' => 'Sudán', 'code' => 'SD', 'is_other' => false],
            ['name' => 'Sudán del Sur', 'code' => 'SS', 'is_other' => false],
            ['name' => 'Suecia', 'code' => 'SE', 'is_other' => false],
            ['name' => 'Suiza', 'code' => 'CH', 'is_other' => false],
            ['name' => 'Surinam', 'code' => 'SR', 'is_other' => false],
            ['name' => 'Svalbard y Jan Mayen', 'code' => 'SJ', 'is_other' => false],
            ['name' => 'Tailandia', 'code' => 'TH', 'is_other' => false],
            ['name' => 'Taiwán (República de China)', 'code' => 'TW', 'is_other' => false],
            ['name' => 'Tanzania', 'code' => 'TZ', 'is_other' => false],
            ['name' => 'Tayikistán', 'code' => 'TJ', 'is_other' => false],
            ['name' => 'Territorio Británico del Océano Índico', 'code' => 'IO', 'is_other' => false],
            ['name' => 'Tierras Australes y Antárticas Francesas', 'code' => 'TF', 'is_other' => false],
            ['name' => 'Timor Oriental', 'code' => 'TL', 'is_other' => false],
            ['name' => 'Togo', 'code' => 'TG', 'is_other' => false],
            ['name' => 'Tokelau', 'code' => 'TK', 'is_other' => false],
            ['name' => 'Tonga', 'code' => 'TO', 'is_other' => false],
            ['name' => 'Trinidad y Tobago', 'code' => 'TT', 'is_other' => false],
            ['name' => 'Túnez', 'code' => 'TN', 'is_other' => false],
            ['name' => 'Turkmenistán', 'code' => 'TM', 'is_other' => false],
            ['name' => 'Turquía', 'code' => 'TR', 'is_other' => false],
            ['name' => 'Tuvalu', 'code' => 'TV', 'is_other' => false],
            ['name' => 'Ucrania', 'code' => 'UA', 'is_other' => false],
            ['name' => 'Uganda', 'code' => 'UG', 'is_other' => false],
            ['name' => 'Uruguay', 'code' => 'UY', 'is_other' => false],
            ['name' => 'Uzbekistán', 'code' => 'UZ', 'is_other' => false],
            ['name' => 'Vanuatu', 'code' => 'VU', 'is_other' => false],
            ['name' => 'Ciudad del Vaticano', 'code' => 'VA', 'is_other' => false],
            ['name' => 'Venezuela', 'code' => 'VE', 'is_other' => false],
            ['name' => 'Vietnam', 'code' => 'VN', 'is_other' => false],
            ['name' => 'Wallis y Futuna', 'code' => 'WF', 'is_other' => false],
            ['name' => 'Yemen', 'code' => 'YE', 'is_other' => false],
            ['name' => 'Yibuti', 'code' => 'DJ', 'is_other' => false],
            ['name' => 'Zambia', 'code' => 'ZM', 'is_other' => false],
            ['name' => 'Zimbabue', 'code' => 'ZW', 'is_other' => false],

            ['name' => 'Otros', 'code' => '', 'is_other' => true],
        ];

        foreach ($countries as &$country) {
            $country['created_at'] = $now;
            $country['updated_at'] = $now;
        }

        DB::table('countries')->insert($countries);
        
        // Obtener el id de Chile
        $chile_id = DB::table('countries')->where('name', 'Chile')->value('id');

        // Insertar las ciudades por región
        $ciudades = [
            'Arica y Parinacota' => [
                'Arica',
                'Putre',
            ],
            'Tarapacá' => [
                'Área Metropolitana Alto Hospicio-Iquique',
                'Pozo Almonte',
            ],
            'Antofagasta' => [
                'Antofagasta',
                'Mejillones',
                'Taltal',
                'Calama',
                'San Pedro de Atacama',
                'Tocopilla',
            ],
            'Atacama' => [
                'Copiapó',
                'Caldera',
                'Tierra Amarilla',
                'Chañaral',
                'Diego de Almagro',
                'El Salvador',
                'Vallenar',
                'Huasco',
            ],
            'Coquimbo' => [
                'Conurbación La Serena-Coquimbo (La Serena y Coquimbo)',
                'Tongoy',
                'Andacollo',
                'Vicuña',
                'Illapel',
                'Los Vilos',
                'Canela',
                'Salamanca',
                'Ovalle',
                'Combarbalá',
                'Monte Patria',
                'El Palqui',
                'Punitaqui',
            ],
            'Valparaíso' => [
                'Gran Valparaíso (Valparaíso, Viña del Mar, Concón, Quilpué y Villa Alemana)',
                'Casablanca',
                'Puchuncaví',
                'Las Ventanas',
                'Quintero',
                'Hanga Roa',
                'Juan Fernández',
                'Los Andes (Los Andes y Calle Larga)',
                'Rinconada',
                'San Esteban',
                'La Ligua',
                'Cabildo',
                'Gran Quillota (Quillota, La Calera, Hijuelas y La Cruz)',
                'Nogales',
                'El Melón',
                'Gran San Antonio (San Antonio, Cartagena, Las Cruces y Santo Domingo)',
                'Algarrobo-El Quisco-El Tabo',
                'Mirasol-El Yeco',
                'San Felipe (San Felipe, Villa Los Almendros y Santa María)',
                'Catemu',
                'Llay-Llay',
                'Putaendo',
                'Limache-Olmué',
            ],
            'O\'Higgins' => [
                'Gran Rancagua (Rancagua, Machalí, Gultro y Los Lirios)',
                'Codegua',
                'Coltauco',
                'Doñihue',
                'Lo Miranda',
                'Graneros',
                'Las Cabras (Las Cabras y Punta Diamante)',
                'San Francisco de Mostazal',
                'La Punta',
                'Peumo',
                'Pichidegua',
                'Quinta de Tilcoco',
                'Rengo',
                'Requínoa',
                'San Vicente de Tagua Tagua',
                'Pichilemu',
                'San Fernando',
                'Chépica',
                'Chimbarongo',
                'Nancagua',
                'Peralillo',
                'Santa Cruz',
            ],
            'Maule' => [
                'Gran Talca (Talca y Maule Norte)',
                'Maule',
                'San Clemente',
                'Constitución',
                'Cauquenes',
                'Curicó',
                'Molina',
                'Hualañé',
                'Rauco',
                'Romeral',
                'Teno',
                'Linares',
                'Colbún',
                'Longaví',
                'Parral',
                'Retiro',
                'San Javier',
                'Villa Alegre',
            ],
            'Ñuble' => [
                'Chillán',
                'Coelemu',
                'Quirihue',
                'Bulnes',
                'Quillón',
                'Yungay',
                'Coihueco',
                'San Carlos',
            ],
            'Biobío' => [
                'Concepción',
                'Talcahuano',
                'Chiguayante',
                'Hualpén',
                'Penco',
                'San Pedro de la Paz',
                
                'Coronel',
                'Hualqui',
                'Lota',
                'Santa Juana',
                'Tomé',
                'Lebu',
                'Arauco',
                'Laraquete',
                'Cañete',
                'Curanilahue',
                'Los Álamos',
                'Contulmo',
                'Los Ángeles',
                'Cabrero',
                'Conurbación La Laja - San Rosendo',
                'Monte Águila',
                'Mulchén',
                'Nacimiento',
                'Santa Bárbara',
                'Huépil',
                'Yumbel',
                'Florida',
            ],
            'Araucanía' => [
                'Temuco',
                'Angol',
                'Padre Las Casas',
                'Villarrica',
                'Victoria',
                'Lautaro',
                'Temuco',
                'Nueva Imperial',
                'Pucón',
                'Pitrufquén',
                'Collipulli',
                'Loncoche',
                'Traiguén',
                'Curacautín',
                'Carahue',
                'Gorbea',
                'Purén',
                'Cunco',
                'Renaico',
                'Vilcún',
                'Cajón',
                'Freire',
            ],
            'Los Ríos' => [
                'Corral',
                'Lanco',
                'Los Lagos',
                'San José de la Mariquina',
                'Paillaco',
                'Panguipulli',
                'La Unión',
                'Futrono',
                'Río Bueno',
                'Valdivi',
            ],
            'Los Lagos' => [
                'Puerto Montt',
                'Alerce',
                'Puerto Varas',
                'Calbuco',
                'Fresia',
                'Frutillar',
                'Los Muermos',
                'Llanquihue',
                'Castro',
                'Ancud',
                'Chonchi',
                'Dalcahue',
                'Quellón',
                'Osorno',
                'Purranque',
                'Río Negro',
                'Chaitén',
            ],
            'Aysén' => [
                'Coyhaique',
                'Puerto Aysén',
                'Cochrane',
                'Chile Chico',
            ],
            'Magallanes' => [
                'Punta Arenas',
                'Puerto Williams',
                'Porvenir',
                'Puerto Natales',
            ],
            'Santiago' => [
                'Gran Santiago',
                'Ciudad del Valle',
                'San José de Maipo',
                'Colina',
                'Lampa',
                'Batuco',
                'Chicauma',
                'Tiltil',
                'Buin',
                'Alto Jahuel',
                'Bajos de San Agustín',
                'Paine',
                'Hospital',
                'Melipilla',
                'Curacaví',
                'Talagante',
                'El Monte',
                'Isla de Maipo',
                'La Islita',
                'Peñaflor',
            ],
            'Otra' => []
        ];

        $regionesIds = [];

        // Insertar regiones y obtener sus IDs
        foreach (array_keys($ciudades) as $region) {
            $regionId = DB::table('regions')->insertGetId([
                'name' => $region,
                'country_id' => $chile_id,
                'is_other' => $region != 'Otra',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        
            $regionesIds[$region] = $regionId;
        }
        
        // Insertar todas las ciudades en un solo batch
        $ciudadesInsert = [];

        foreach ($ciudades as $region => $cities) {
            foreach ($cities as $city) {
                $ciudadesInsert[] = [
                    'name' => $city,
                    'region_id' => $regionesIds[$region],
                    'is_other' => 0,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
            
            // Agregar ciudad "Otra" para esta región
            $ciudadesInsert[] = [
                'name' => 'Otra',
                'region_id' => $regionesIds[$region],
                'is_other' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }
        
        DB::table('cities')->insert($ciudadesInsert);
    }
}
