services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/vendor
    container_name: laravel54_app