ServerName massoeventos.test

<VirtualHost *:80>
    ServerName sistema.massoeventos.test
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>